server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/jwt
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

jwt:
  token:
    secret: qCQBnkCjTLmGCAwR
    expired: 3600000